### ISSUE TITLE
es6

### ISSUE THREAD

**Issue by shaunc** [js2coffee/js2coffee-redux#3]
Would this be a good place to hope for es6 support?

Currently I'm porting a large ember application in litcoffee into ember-cli. I don't want to move to es6 because of how close my doc is tied to the code (and I like it that way...) Many things that ember-cli can generate (especially mocha tests) are in es6. I'm hoping for a way to automate their conversion, and am fine with backticks around import, export, etc.

**Comment by rstacruz** [comment]
yes, absolutely. esprima supports es6 syntax constructs.

**Comment by rstacruz** [comment]
...btw, esprima support for es6 is still a little early: [esprima-harmony](http://npmjs.org/package/esprima-harmony) still doesn't support backticked strings.

I'm looking forward to geting classes translated properly though :)
