### ISSUE TITLE
Continue in for loops

### ISSUE THREAD

**Issue by pronebird** [js2coffee/js2coffee-redux#4]
Update part is never called in for loops when continue used.

``` javascript
for (i = 0; i < 30; ++i) {
  if (true) continue;
}
```

is compiled into:

``` coffee
i = 0
while i < 30
  if true
    continue
  ++i
```

js2coffee reference:
https://github.com/js2coffee/js2coffee/issues/49

**Comment by rstacruz** [comment]
Would this be an acceptable behavior?

``` js
for (a; b; update++) {
  if (true) continue;
}
```

``` coffee
a
while b
  if true
    update++
    continue
  update++
```

Or more complicatedly:

``` js
for (a; b; update++) {
  if (condition1) continue;
  else if (condition2) continue;
}
```

``` coffee
a
while b
  if condition1
    update++
    continue
  else if condition2
    update++
    continue
  update++
```

**Comment by pronebird** [comment]
This is how we have this solved in js2coffee. There is really no better option until we support for loops. So I'd say it's more than acceptable.

**Comment by hsingh23** [comment]
Perhaps this may be a way to solve the problem
i = 0
while i < 30
  j = i
  i ++
  if true
    continue

now use j where ever you see i in the code

  On Sat, Jan 24, 2015 at 6:13 AM, Andrej Mihajlov <notifications@github.com

**Comment by pronebird** [comment]
@hsingh23 

This won't work if you advance loop from body. For example:

``` javascript
for(i = 0; i < 10; i++) {
   if(i === 0) continue;
   if(i === 2) i += 2;
}
```

In your case we'd rewrite it to:

``` coffee
i = 0
while i < 10
  j = i
  i++
  continue  if j is 0
  j += 2  if j is 2
```

it's way simpler to duplicate update statement after each continue in scope.

**Comment by rstacruz** [comment]
Done in v0.0.10 :) [demo](http://js2coffee.github.io/js2coffee-redux/#try:for%20%28a%3Bb%3Bc%2B%2B%29%20{%0A%20%20if%20%28true%29%20continue%0A%20%20if%20%28false%29%20continue%0A})

**Comment by rstacruz** [comment]
Found some cases that js2coffee 0.x chokes on:

![pasted_image_1_25_15__4_12_pm](https://cloud.githubusercontent.com/assets/74385/5890869/0652ebce-a4ad-11e4-8dc1-8711a7389cfd.png)

Fixed in redux: [demo](http://js2coffee.github.io/js2coffee-redux/#try:for%28%3B%20%3B%20el.outerWidth%29%20{%0A%20%20if%20%28x%29%20continue%3B%0A%20%20continue%3B%0A})

**Comment by pronebird** [comment]
Incoming AST from narcissus has a very inconsistent structure so the common problem I had there was to take the update part and wrap it in statement before inserting into AST. But then certain updates are treated as statements, others as inline, etc.. It's a mess.

—
Cheers,
Andrej
