### ISSUE TITLE
Object conversion error

### ISSUE THREAD

**Issue by pronebird** [js2coffee/js2coffee-redux#6]
``` javascript
var object = {
  sayHello,
  sayGoodbye
};
```

converted as:

``` coffee
object = 
  sayHello: sayHello
  sayGoodbye: sayGoodbye
```

Why is this legal?

**Comment by rstacruz** [comment]
Because `{a,b}` is perfectly valid es6 ;)

http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&code=var%20object%20%3D%20{%0A%20%20sayHello%2C%0A%20%20sayGoodbye%0A}%3B
